# Generated by Django 4.1.2 on 2022-11-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuessDistribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('games_played', models.IntegerField()),
                ('games_won', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('games_played', models.IntegerField()),
                ('games_won', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=10)),
                ('is_chosen', models.BooleanField(default=False)),
                ('date_chosen', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
