# Generated by Django 4.1.2 on 2022-10-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuol_wordle_api", "0002_stats_word_date_chosen"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalStats",
            fields=[("id", models.IntegerField(primary_key=True, serialize=False)),],
        ),
        migrations.CreateModel(
            name="UserStats",
            fields=[("id", models.IntegerField(primary_key=True, serialize=False)),],
        ),
        migrations.DeleteModel(name="Stats",),
    ]
